name: volleyball_coaching_app
description: A volleyball coaching app for positions and rotations
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  
  # State Management
  flutter_riverpod: ^3.0.3
  
  # Navigation
  go_router: ^17.0.0
  
  # UI
  cupertino_icons: ^1.0.6
  
  # URL Launcher
  url_launcher: ^6.2.5
  
  # UUID
  uuid: ^4.5.1
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Supabase
  supabase_flutter: ^2.0.0
  sqflite: ^2.4.2
  path: ^1.9.1
  share_plus: ^12.0.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true

